homeassistant: false
permit_join: false

mqtt:
  server: mqtt://127.0.0.1:1883
  base_topic: zigbee2mqtt

serial:
  adapter: ember
  port: /dev/serial/by-id/your-sonoff-dongle

frontend:
  enabled: false

advanced:
  log_level: info

device_options: {}
